// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xienswzlznagfkkykmvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZW5zd3psem5hZ2Zra3lrbXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDMyMDksImV4cCI6MjA1MTY3OTIwOX0.ReBr3E1hX-sp_CYyvcHPk5fe4ssXg69aVSXhjQ4Rtbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);